### ISSUE TITLE
Current examples will fail on PHP 5.2.x and 5.3.x

### ISSUE THREAD

**Issue by robneu** [gamajo/registerable#3]
The short array syntax wasn't introduced until [PHP 5.4](http://php.net/releases/5_4_0.php), so the current examples will produce fatal errors for anyone running an older version.

You could bump the version requirement, but it seems like a somewhat trivial thing to force 5.4+

**Comment by GaryJones** [comment]
Sorry - 5.4 is at the least the minimum I support now for this. The project I'm using this on uses PHP 5.6, so I've got no interest in supporting older.

The https://github.com/GaryJones/Gamajo-Registerable project still exists for this reason - it has the same end effect, but is backwards compatible for PHP 5.2.

**Comment by robneu** [comment]
Ahhh okay. Sorry for the confusion. I thought I'd seen this code before, but didn't make the connection. :+1:

**Comment by GaryJones** [comment]
https://github.com/gamajo/registerable#compatibility :-)
